name: alzheimers_project
channels:
  - defaults
  - conda-forge
dependencies:
  - poetry
  - pandas
  - seaborn
  - matplotlib
  - numpy
  - tqdm
  - imageio
  - scikit-learn
  - notebook
  - jupyterlab
  - scikit-image
  - tensorflow
  - opencv
  - imbalanced-learn